[package]
name = "hde"
version = "0.1.0"
authors = ["David Begin <davidmichaelbe@gmail.com>"]

[dependencies]
type_printer = "*"
postgres = "*"
csv = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
